#!/usr/bin/env node

import fs from 'node:fs';
import path from 'node:path';

const repoRoot = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');

const AUTH_JSON_PATH = path.join(repoRoot, 'src', 'core', 'generated', 'feishu-tool-auth.json');
const AUTH_TS_PATH = path.join(repoRoot, 'src', 'core', 'generated', 'feishu-tool-auth.ts');
const SCOPE_SPECS_JSON_PATH = path.join(repoRoot, 'src', 'core', 'generated', 'feishu-tool-scope-specs.json');
const SCOPE_SPECS_TS_PATH = path.join(repoRoot, 'src', 'core', 'generated', 'feishu-tool-scope-specs.ts');
const SCOPES_JSON_PATH = path.join(repoRoot, 'src', 'core', 'generated', 'feishu-tool-scopes.json');
const SCOPES_TS_PATH = path.join(repoRoot, 'src', 'core', 'generated', 'feishu-tool-scopes.ts');
const TOOL_ACTION_KEYS_TS_PATH = path.join(repoRoot, 'src', 'core', 'generated', 'feishu-tool-action-keys.ts');

// Runtime still has a small number of internal tool actions that do not come
// from the official endpoint/scope/auth snapshots. Keep the exception list
// explicit and small until those actions can be folded into canonical metadata.
const MANUAL_TOOL_ACTION_KEY_EXTRAS = ['feishu_get_user.basic_batch'];

function parseArgs(argv) {
  return {
    write: !argv.includes('--check'),
  };
}

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function writeIfChanged(filePath, content, write) {
  const next = typeof content === 'string' ? content : `${JSON.stringify(content, null, 2)}\n`;
  const prev = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : null;

  if (prev === next) {
    return false;
  }

  if (!write) {
    throw new Error(`Generated file is out of date: ${path.relative(repoRoot, filePath)}`);
  }

  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, next);
  return true;
}

function stableObjectFromEntries(entries) {
  return Object.fromEntries([...entries].sort(([left], [right]) => left.localeCompare(right)));
}

function stableUniqueStrings(values) {
  return [...new Set(values)].sort((left, right) => left.localeCompare(right));
}

function normalizeAuthMap(rawAuthMap) {
  const entries = Object.entries(rawAuthMap).map(([toolAction, authModes]) => {
    if (!Array.isArray(authModes) || authModes.some((mode) => typeof mode !== 'string' || mode.trim().length === 0)) {
      throw new Error(`Invalid auth modes for ${toolAction}`);
    }

    return [toolAction, [...new Set(authModes.map((mode) => mode.trim()))]];
  });

  return stableObjectFromEntries(entries);
}

function normalizeScopeSpecs(rawScopeSpecs) {
  const entries = Object.entries(rawScopeSpecs).map(([toolAction, spec]) => {
    if (!spec || typeof spec !== 'object') {
      throw new Error(`Invalid scope spec for ${toolAction}`);
    }

    const requiredScopes = spec.requiredScopes;
    const scopeNeedType = spec.scopeNeedType;
    const source = spec.source;

    if (
      !Array.isArray(requiredScopes) ||
      requiredScopes.some((scope) => typeof scope !== 'string' || scope.trim().length === 0)
    ) {
      throw new Error(`Invalid requiredScopes for ${toolAction}`);
    }

    if (scopeNeedType !== 'one' && scopeNeedType !== 'all') {
      throw new Error(`Invalid scopeNeedType for ${toolAction}: ${String(scopeNeedType)}`);
    }

    if (source !== 'official' && source !== 'manual') {
      throw new Error(`Invalid source for ${toolAction}: ${String(source)}`);
    }

    return [
      toolAction,
      {
        requiredScopes: [...requiredScopes],
        scopeNeedType,
        source,
      },
    ];
  });

  return stableObjectFromEntries(entries);
}

function buildScopesFromSpecs(scopeSpecs) {
  return stableObjectFromEntries(
    Object.entries(scopeSpecs).map(([toolAction, spec]) => [toolAction, [...spec.requiredScopes]]),
  );
}

function buildToolActionKeys({ authMap, scopeSpecs, scopes }) {
  return stableUniqueStrings([
    ...Object.keys(authMap),
    ...Object.keys(scopeSpecs),
    ...Object.keys(scopes),
    ...MANUAL_TOOL_ACTION_KEY_EXTRAS,
  ]);
}

function renderAuthTs() {
  return `/**
 * Copyright (c) 2026 ByteDance Ltd. and/or its affiliates
 * SPDX-License-Identifier: MIT
 *
 * Generated by \`scripts/refresh_feishu_runtime_metadata.mjs\`.
 * Do not edit manually.
 */

import rawGeneratedToolAuthModes from './feishu-tool-auth.json';

export const GENERATED_TOOL_AUTH_MODES = rawGeneratedToolAuthModes as Record<string, readonly string[]>;
export const GENERATED_TOOL_AUTH_COUNT = Object.keys(GENERATED_TOOL_AUTH_MODES).length;
`;
}

function renderScopesTs() {
  return `/**
 * Copyright (c) 2026 ByteDance Ltd. and/or its affiliates
 * SPDX-License-Identifier: MIT
 *
 * Generated by \`scripts/refresh_feishu_runtime_metadata.mjs\`.
 * Do not edit manually.
 */

import rawGeneratedToolScopes from './feishu-tool-scopes.json';

export const GENERATED_TOOL_SCOPES = rawGeneratedToolScopes as Record<string, readonly string[]>;
export const GENERATED_TOOL_SCOPE_COUNT = Object.keys(GENERATED_TOOL_SCOPES).length;
`;
}

function renderScopeSpecsTs() {
  return `/**
 * Copyright (c) 2026 ByteDance Ltd. and/or its affiliates
 * SPDX-License-Identifier: MIT
 *
 * Generated by \`scripts/refresh_feishu_runtime_metadata.mjs\`.
 * Do not edit manually.
 */

import rawGeneratedToolScopeSpecs from './feishu-tool-scope-specs.json';

export interface GeneratedToolScopeSpec {
  requiredScopes: readonly string[];
  scopeNeedType: 'one' | 'all';
  source: 'official' | 'manual';
}

export const GENERATED_TOOL_SCOPE_SPECS = rawGeneratedToolScopeSpecs as Record<string, GeneratedToolScopeSpec>;
export const GENERATED_TOOL_SCOPE_SPEC_COUNT = Object.keys(GENERATED_TOOL_SCOPE_SPECS).length;
`;
}

function renderToolActionKeysTs(toolActionKeys) {
  const lines = toolActionKeys.map((toolAction) => `  '${toolAction}',`).join('\n');
  return `/**
 * Copyright (c) 2026 ByteDance Ltd. and/or its affiliates
 * SPDX-License-Identifier: MIT
 *
 * Generated by \`scripts/refresh_feishu_runtime_metadata.mjs\`.
 * Do not edit manually.
 */

export const GENERATED_TOOL_ACTION_KEYS = [
${lines}
] as const;

export type GeneratedToolActionKey = (typeof GENERATED_TOOL_ACTION_KEYS)[number];
export const GENERATED_TOOL_ACTION_KEY_COUNT = GENERATED_TOOL_ACTION_KEYS.length;
`;
}

function main() {
  const args = parseArgs(process.argv.slice(2));

  const normalizedAuthMap = normalizeAuthMap(readJson(AUTH_JSON_PATH));
  const normalizedScopeSpecs = normalizeScopeSpecs(readJson(SCOPE_SPECS_JSON_PATH));
  const normalizedScopes = buildScopesFromSpecs(normalizedScopeSpecs);
  const toolActionKeys = buildToolActionKeys({
    authMap: normalizedAuthMap,
    scopeSpecs: normalizedScopeSpecs,
    scopes: normalizedScopes,
  });

  writeIfChanged(AUTH_JSON_PATH, normalizedAuthMap, args.write);
  writeIfChanged(SCOPE_SPECS_JSON_PATH, normalizedScopeSpecs, args.write);
  writeIfChanged(SCOPES_JSON_PATH, normalizedScopes, args.write);
  writeIfChanged(AUTH_TS_PATH, renderAuthTs(), args.write);
  writeIfChanged(SCOPE_SPECS_TS_PATH, renderScopeSpecsTs(), args.write);
  writeIfChanged(SCOPES_TS_PATH, renderScopesTs(), args.write);
  writeIfChanged(TOOL_ACTION_KEYS_TS_PATH, renderToolActionKeysTs(toolActionKeys), args.write);
}

try {
  main();
} catch (error) {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
}
